project:
  type: website
  output-dir: docs

website:
  title: "Christine Winther Bang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: research.qmd
        text: Research
    tools:      
      - icon: envelope-fill
        href: mailto:cwb@math.ku.dk
format:
  html:
    theme: flatly
    linkcolor: "#658C58"
    mainfont: helvetica
